name: check-coverage-by-codecov

on:
  push:
    branches:
      - '*'
    pull_request:
      types: [ opened, synchronize, reopened ]

jobs:
  check-coverage-by-codecov:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v1
      - name: set-up-JDK-8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: maven-verify
        run: mvn -B clean verify
      - name: check-coverage-by-codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}