name: verify-labels-in-pr

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/match-label-action@v2
        with:
          allowed: 'type:fix, type:features, type:documentation, type:tests, type:config'